# Generated by Django 4.2.1 on 2023-11-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationsQuestionsResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_18', models.TextField()),
                ('question_19', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EducationQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_20', models.TextField()),
                ('question_21', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformationQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.TextField()),
                ('question_2', models.TextField()),
                ('question_3', models.TextField()),
                ('question_4', models.TextField()),
                ('question_5', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSkillsQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_15', models.TextField()),
                ('question_16', models.TextField()),
                ('question_17', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperienceQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_9', models.TextField()),
                ('question_10', models.TextField()),
                ('question_11', models.TextField()),
                ('question_12', models.TextField()),
                ('question_13', models.TextField()),
                ('question_14', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='UserResponse',
            new_name='ProfessionalSummaryQuestionResponse',
        ),
        migrations.RenameField(
            model_name='professionalsummaryquestionresponse',
            old_name='question_1',
            new_name='question_6',
        ),
        migrations.RenameField(
            model_name='professionalsummaryquestionresponse',
            old_name='question_2',
            new_name='question_7',
        ),
        migrations.RenameField(
            model_name='professionalsummaryquestionresponse',
            old_name='question_3',
            new_name='question_8',
        ),
    ]
